### PR TITLE
Enabling es6 features in eslint

### PR DESCRIPTION
**Pull request by AndrewRayCode**
There is [a related Banyan PR](https://github.com/ConsultingMD/banyan/pull/445)
where we're trying to remove the hard coded linting files and instead
use our centralized ones, but Banyan (and other repos) requires ES6
linting enbaled, which isn't yet in this tool

### CODE REVIEW

**Comment by etripier** [comment]
I think we should standardize around the `airbnb` config (might as well if we're going to enforce some ES6 rules here). The config might end up looking like this:

```
module.exports = {
  env: {
    amd: true,
    browser: true,
    commonjs: true,
    jquery: true,
    node: true
  },
  extends: ['airbnb'],
```

What do you think? @RoryO @AndrewRayCode

**Comment by RoryO** [comment]
Does that mean that when airbnb makes changes existing code will become invalid?

**Comment by etripier** [comment]
Yes, existing code will be flagged with new errors.

**Comment by RoryO** [comment]
That will end up surprising. Like when npm packages suddenly changed when not using yarn.

**Comment by etripier** [comment]
We can version our `airbnb` config using Yarn, so I don't expect that to be a huge issue. I'm more worried about CodeClimate's integration of the config - they actually sandbox the NPM package for the config, so they may not have the exact version we're using.

I still think we should make every effort to standardize around a comprehensive config. JavaScript evolves pretty quickly, so it'd be nice to cover newer features of the language without having to do a ton of work looking up new rules.

**Comment by AndrewRayCode** [comment]
@etripier Change made. I agree standardizing on airbnb config is fine. I also added the necessary airbnb eslint plugins to the package.json of Banyan [in the related PR](https://github.com/ConsultingMD/banyan/pull/445).

@andrewpurcell This is our proposed change to centrally standardize Javascript linting across our projects, by simply using the well known [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) config. It has buy-in from Etienne, Rory and I.

Currently, the project this mainly effects is Banyan. There is a [related PR](https://github.com/ConsultingMD/banyan/pull/445) to remove Banyan's local linting files and use our standardized central coding styles provided by this repo / Codeclimate. However, this means Banyan will now start showing many warnings in Codeclimate, which I believe will all look like they started on [the Banyan PR](https://github.com/ConsultingMD/banyan/pull/445).

Other than introducing eslint warnings (not errors), I think we should standardize sooner rather than later. For addressing the eslint warnings, I propose a "fix as you go" style which we more or less do with some other repos currently.

(It doesn't look like I can add reviewers to this PR as I'm not an owner of this repo)

**Comment by andrewpurcell** [comment]
Are we choosing airbnb because we agree with all of their choices, or because it's easier for maintaining and keeping up to date?

**Comment by AndrewRayCode** [comment]
@andrewpurcell The latter. Their choices will enforce a few things we don't currently do in our JS code, but no actual functional changes.

Etienne and I are looking at this the following way (duplicating some of the convos above):
- We don't want to be in the business of tracking the evolving Javascript language syntax and hand-managing linting rules around that.
- Figuring out which rules to override locally per repo won't be developer time we worry about any more, since we'll fall back on airbnb for everything. For example, we will remove our [custom Jarvis eslint rules](https://github.com/ConsultingMD/jarvis/blob/master/client/.eslintrc.js#L20-L21)
- We should standardize our coding style at some point, and there's no benefit to putting it off, we'll only get more entrenched in one-off per-project linting configs
- The non-style changes downstream changes of this are manageable. For example, airbnb enforces the file extension `.jsx` for files containing jsx, which we don't currently do. When we later rename those files, we'll have to update our test framework "jest" to include .jsx files for testing, not just .js. This is the only non-style downstream change we know of so far.

Feel free to add any other relevant details @etripier

**Comment by etripier** [comment]
Are there outstanding concerns about merging this?

**Comment by RoryO** [comment]
Only the concern that users will get Sudden Code Climate happening when AirBnB updates.

**Comment by AndrewRayCode** [comment]
@RoryO Not having this merged is starting to cause friction in other projects. I've talked it over with etienne and we want to merge this now so that developers have sane local development linting tools. happy to discuss this more in person if you want.

**Pull request merged**
